### ISSUE TITLE
Use const/let instead of var

### ISSUE THREAD

**Issue by ccarmesin** [Zero3141/FridaOkHttpBypass#1]
Please use const and let instead of var. It's more efficient when it comes to stroage allocation ;-).
More information: https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

**Comment by Zero3141** [comment]
Fixed in https://github.com/Zero3141/Frida-OkHttp-Bypass/commit/817a72166cc1be21cf06069474521d8593aea300
